dist: trusty
sudo: required
language: node_js
node_js: node
addons:
  firefox: latest
  chrome: stable
branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - sudo apt-get install -y dbus-x11
  - npm install -g bower cross-zip-cli
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install: npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run test
  - npm run lint || true
  - npm run bundle
  - mv build video-player-$TRAVIS_TAG
  - cross-zip video-player-$TRAVIS_TAG video-player-$TRAVIS_TAG.zip
deploy:
  provider: releases
  api_key:
    secure: PGi29wD0hxjnYvMi3DJA5cR/dXztb407yvq1ggKq9vAp0HX+nC4mYptjjRBlddWNBfO6d4XGtuCWgBZ46uLjE7yZW/h6e/OCUhmR05ddzBE6lXect22RfEOl4hoABWNGSXzpI8rzzQkgJ0lLBB/R6qTIQczuPLzqgf45QHw1nX9mY4lYlbGTGimLD0Jt3jJDG/uOP3wLXMNCEqAJ0NQ80X2Ydy/KYiOhcxiZTZa8iybtle4Bl4Ks9GNWJaOWwr2vaG4nKFnmEBCoq42ECz87u6P2c1asNv5560JF4oj59wHBnXIDPfr5uJRwxbIpFqRgLuskqHCde68xdNMD0jlss4U1QJ5DGoWPdGcyys9wXWOmCR0JYIB5rzUce3xVdkUKHnEf9K1u8ULxdA++aTzxAxbHrtYNLXedzlCNcLifHDRV1MwQiBCu4rDRuWZvLH4+FQ1su7oj6CMFLKoT8vafUGY/9M9pmFa+ZGTm3h3pMccRk8GV03fH1fIPsX3ScLNgCov7+n9hajIsVsLCl3d8+6omN43ikbH5tJopy3tSAC4gu4wdAwZbRn7cq1EjbGrn5AIZbQQPFwMO3IX5IXAfCbP1pwi+qFMLUOPijEtU39HYXzJ4lgebdNBI7IRcHIm9ihCDG32MBg5xSejc1aYM/QXt2VaocEada5W8xTqsERA=
  skip_cleanup: true
  file: video-player-$TRAVIS_TAG.zip
  on:
    repo: openHPI/video-player
    tags: true
